import "~/styles/globals.css";
import { ToastContainer} from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Navbar } from "./_components/navbar";
import { Announcement } from "./_components/announcement";
import { AuthProvider } from "~/context/AuthContext";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <AuthProvider>
        <ToastContainer
        theme="dark"
        />
        <Navbar/>
        <Announcement/>
        <TRPCReactProvider>{children}</TRPCReactProvider>
        </AuthProvider>
        <script src="https://kit.fontawesome.com/6e9847b298.js" crossOrigin="anonymous"></script>
      </body>
    </html>
  );
}
